# Generated by Django 5.0.4 on 2025-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_event_price_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('refreq', 'Запрошен возврат'), ('refunded', 'Возвращён'), ('cancelled', 'Отменён'), ('used', 'Использован')], default='paid', max_length=12),
        ),
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
