"""
Django settings for project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

import os
from pathlib import Path
from datetime import timedelta  # 👈 добавили для AXES_COOLOFF_TIME

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%w(0du&_zb#r(&9g=#)^=0z81ei1or$i6)r(g6f*@_aetf8#8='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # сторонние
    'axes',              # 👈 защита от bruteforce
    'django_apscheduler',

    # твои приложения
    'accounts',
    'services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'axes.middleware.AxesMiddleware',  # ← вот сюда

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

SITE_URL = "http://127.0.0.1:8000"


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'


# ========= EMAIL (для восстановления пароля и писем с билетами) =========

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nonegivenalmau@gmail.com'
EMAIL_HOST_PASSWORD = 'fiycgblqapjwlbtk'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# от кого будут уходить письма
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ========= CORS / CSRF (оставляем как у тебя) =========

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://*",
    "https://*",
    "https://config.up.railway.app/*",
    "http://config.up.railway.app/*"
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ========= JAZZMIN (админка) =========

JAZZMIN_SETTINGS = {
    "site_title": "CityTickets Admin",
    "site_header": "CityTickets",
    "site_brand": "CityTickets",

    "topmenu_links": [
        {"name": "На сайт", "url": "home", "new_window": True},
        {"name": "События", "url": "events"},
    ],

    "usermenu_links": [
        {"name": "На сайт", "url": "home", "new_window": True},
    ],
}


# ========= СЕССИИ (сколько живёт логин) =========
# 24 часа авторизации
SESSION_COOKIE_AGE = 24 * 60 * 60  # 24 часа

# Куда кидать неавторизованных юзеров
LOGIN_URL = 'home'   # это name из urls: path('', ..., name='home')



# ========= AUTHENTICATION_BACKENDS (подключаем Axes) =========

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',                  # Axes + get_user
    'django.contrib.auth.backends.ModelBackend',
]


# ========= django-axes: защита от bruteforce =========

AXES_ENABLED = False
#AXES_ENABLED = True

# сколько неудачных попыток до бана
AXES_FAILURE_LIMIT = 20

# на сколько блокируем IP
AXES_COOLOFF_TIME = timedelta(minutes=15)

# блокируем по IP (как ты хотел)
AXES_LOCKOUT_PARAMETERS = ['ip_address']

# сбрасывать счётчик после успешного входа
AXES_RESET_ON_SUCCESS = True

# считаем только реальные провалы авторизации
# AXES_ONLY_USER_FAILURES = True
AXES_ONLY_AUTHENTICATION_FAILURES = True
